// WebGPU 2D Shaders
// テクスチャ生成用のシェーダーをエクスポート

export { TextureRenderer, type PostEffectSpec, type DualTextureSpec } from './TextureRenderer'

// Surface Mask shader (two-texture)
export { createSurfaceMaskSpec, surfaceMaskShader } from './shaders/surfaceMask'

// Overlay Blend shader (two-texture alpha compositing)
export { createOverlayBlendSpec, overlayBlendShader, OVERLAY_BLEND_BUFFER_SIZE } from './shaders/overlayBlend'

// Shader types and createSpec functions
export type {
  SolidTextureParams,
  StripeTextureParams,
  GridTextureParams,
  PolkaDotTextureParams,
  CheckerTextureParams,
  TriangleTextureParams,
  HexagonTextureParams,
  CircleMaskParams,
  RectMaskParams,
  BlobMaskParams,
  PerlinMaskParams,
  SimplexMaskParams,
  CurlMaskParams,
  LinearGradientMaskParams,
  RadialGradientMaskParams,
  BoxGradientMaskParams,
  WavyLineMaskParams,
  // Masked texture types
  MaskType,
  TextureType,
  CircleMaskConfig,
  RectMaskConfig,
  BlobMaskConfig,
  PerlinMaskConfig,
  MaskConfig,
  StripeTextureConfig,
  GridTextureConfig,
  PolkaDotTextureConfig,
  CheckerTextureConfig,
  TextureConfig,
  MaskedTextureParams,
  GradientGrainTextureConfig,
  // Gradient types
  LinearGradientParams,
  ColorStop,
  GradientGrainLinearParams,
  GradientGrainCircularParams,
  GradientGrainRadialParams,
  GradientGrainPerlinParams,
  GradientGrainCurlParams,
  GradientGrainSimplexParams,
  LinearDepthMapParams,
  CircularDepthMapParams,
  RadialDepthMapParams,
  PerlinDepthMapParams,
  NoiseMapParams,
  GradientNoiseMapParams,
  IntensityCurveParams,
  DepthMapType,
  // Clip mask types
  ClipMaskBaseParams,
  CircleClipParams,
  RectClipParams,
  BlobClipParams,
  PerlinClipParams,
  LinearGradientClipParams,
  RadialGradientClipParams,
  BoxGradientClipParams,
  ClipMaskParams,
} from './shaders'

export {
  createSolidSpec,
  createStripeSpec,
  createGridSpec,
  createPolkaDotSpec,
  createCheckerSpec,
  createTriangleSpec,
  createHexagonSpec,
  // Textile pattern specs
  createAsanohaSpec,
  createSeigaihaSpec,
  createWaveSpec,
  createScalesSpec,
  createOgeeSpec,
  createSunburstSpec,
  createCircleMaskSpec,
  createRectMaskSpec,
  createBlobMaskSpec,
  createPerlinMaskSpec,
  createSimplexMaskSpec,
  createCurlMaskSpec,
  createLinearGradientMaskSpec,
  createRadialGradientMaskSpec,
  createBoxGradientMaskSpec,
  createWavyLineMaskSpec,
  // Greymap mask specs (2-stage pipeline)
  createCircleGreymapMaskSpec,
  createRectGreymapMaskSpec,
  createBlobGreymapMaskSpec,
  createPerlinGreymapMaskSpec,
  createLinearGradientGreymapMaskSpec,
  createRadialGradientGreymapMaskSpec,
  createBoxGradientGreymapMaskSpec,
  // Colorize spec
  createColorizeSpec,
  createMaskColorizeParams,
  // Masked texture specs
  createCircleStripeSpec,
  createCircleGridSpec,
  createCirclePolkaDotSpec,
  createCircleCheckerSpec,
  createRectStripeSpec,
  createRectGridSpec,
  createRectPolkaDotSpec,
  createRectCheckerSpec,
  createBlobStripeSpec,
  createBlobGridSpec,
  createBlobPolkaDotSpec,
  createBlobCheckerSpec,
  createPerlinStripeSpec,
  createPerlinGridSpec,
  createPerlinPolkaDotSpec,
  createPerlinCheckerSpec,
  // Masked GradientGrain specs
  createCircleGradientGrainSpec,
  createRectGradientGrainSpec,
  createBlobGradientGrainSpec,
  // Gradient specs
  createLinearGradientSpec,
  createGradientGrainLinearSpec,
  createGradientGrainCircularSpec,
  createGradientGrainRadialSpec,
  createGradientGrainPerlinSpec,
  createGradientGrainCurlSpec,
  createGradientGrainSimplexSpec,
  createLinearDepthMapSpec,
  createCircularDepthMapSpec,
  createRadialDepthMapSpec,
  createPerlinDepthMapSpec,
  createNoiseMapSpec,
  createGradientNoiseMapSpec,
  createIntensityCurveSpec,
  // Clip mask specs
  createCircleClipSpec,
  createRectClipSpec,
  createBlobClipSpec,
  createPerlinClipSpec,
  createLinearGradientClipSpec,
  createRadialGradientClipSpec,
  createBoxGradientClipSpec,
  createClipMaskSpec,
} from './shaders'

// Filter specs are now available via '@practice/texture/filters'
// import { vignetteShader, createVignetteUniforms, chromaticAberrationShader } from '@practice/texture/filters'

// Domain
export type {
  RGBA,
  TextureRenderOptions,
  Viewport,
  TexturePattern,
  TextureRenderSpec,
  MaskShapeType,
  CircleMaskShapeConfig,
  RectMaskShapeConfig,
  BlobMaskShapeConfig,
  PerlinMaskShapeConfig,
  SimplexMaskShapeConfig,
  CurlMaskShapeConfig,
  LinearGradientMaskShapeConfig,
  RadialGradientMaskShapeConfig,
  BoxGradientMaskShapeConfig,
  WavyLineMaskShapeConfig,
  MaskShapeConfig,
  MaskPattern,
  // Greymap types (2-stage mask pipeline)
  GreymapMaskSpec,
  GreymapMaskParams,
  CircleGreymapMaskParams,
  RectGreymapMaskParams,
  BlobGreymapMaskParams,
  PerlinGreymapMaskParams,
  LinearGradientGreymapMaskParams,
  RadialGradientGreymapMaskParams,
  BoxGradientGreymapMaskParams,
  ColorizeParams,
  // Surface Presets
  SurfacePresetType,
  SolidPresetParams,
  StripePresetParams,
  GridPresetParams,
  PolkaDotPresetParams,
  CheckerPresetParams,
  GradientGrainLinearPresetParams,
  GradientGrainCircularPresetParams,
  GradientGrainRadialPresetParams,
  GradientGrainPerlinPresetParams,
  GradientGrainCurlPresetParams,
  GradientGrainSimplexPresetParams,
  TrianglePresetParams,
  HexagonPresetParams,
  SurfacePresetParams,
  SurfacePreset,
  // TexturePatternSpec types
  TexturePatternSpec,
  TexturePatternParams,
  SimpleTexturePatternParams,
  MaskPatternParams,
  MaskedTexturePatternParams,
  FilterPatternParams,
  SolidPatternParams,
  StripePatternParams,
  GridPatternParams,
  PolkaDotPatternParams,
  CircleMaskPatternParams,
  RectMaskPatternParams,
  CircleStripePatternParams,
  CircleGridPatternParams,
  CirclePolkaDotPatternParams,
  RectStripePatternParams,
  RectGridPatternParams,
  RectPolkaDotPatternParams,
  BlobStripePatternParams,
  BlobGridPatternParams,
  BlobPolkaDotPatternParams,
  VignettePatternParams,
  ChromaticAberrationPatternParams,
  // Schema param types
  CircleMaskShapeParams,
  RectMaskShapeParams,
  BlobMaskShapeParams,
  PerlinMaskShapeParams,
  SimplexMaskShapeParams,
  CurlMaskShapeParams,
  LinearGradientMaskShapeParams,
  RadialGradientMaskShapeParams,
  BoxGradientMaskShapeParams,
  WavyLineMaskShapeParams,
  SolidSurfaceParams,
  StripeSurfaceParams,
  GridSurfaceParams,
  PolkaDotSurfaceParams,
  CheckerSurfaceParams,
  TriangleSurfaceParams,
  HexagonSurfaceParams,
} from './Domain'

// Shape and Surface Schemas
export {
  // Shape Schemas
  CircleMaskShapeSchema,
  RectMaskShapeSchema,
  BlobMaskShapeSchema,
  PerlinMaskShapeSchema,
  SimplexMaskShapeSchema,
  CurlMaskShapeSchema,
  MaskShapeSchemas,
  // Surface Schemas
  SolidSurfaceSchema,
  StripeSurfaceSchema,
  GridSurfaceSchema,
  PolkaDotSurfaceSchema,
  CheckerSurfaceSchema,
  GradientGrainLinearSurfaceSchema,
  GradientGrainCircularSurfaceSchema,
  GradientGrainRadialSurfaceSchema,
  GradientGrainPerlinSurfaceSchema,
  GradientGrainCurlSurfaceSchema,
  GradientGrainSimplexSurfaceSchema,
  SurfaceSchemas,
  // Constants
  DEFAULT_GRADIENT_GRAIN_CURVE_POINTS,
  // Factory functions
  createDefaultCircleMaskParams,
  createDefaultRectMaskParams,
  createDefaultBlobMaskParams,
  createDefaultPerlinMaskParams,
  createDefaultSimplexMaskParams,
  createDefaultCurlMaskParams,
  createDefaultSolidParams,
  createDefaultStripeParams,
  createDefaultGridParams,
  createDefaultPolkaDotParams,
  createDefaultCheckerParams,
  createDefaultGradientGrainLinearParams,
  createDefaultGradientGrainCircularParams,
  createDefaultGradientGrainRadialParams,
  createDefaultGradientGrainPerlinParams,
  createDefaultGradientGrainCurlParams,
  createDefaultGradientGrainSimplexParams,
} from './Domain'

// Re-export getDefaults from @practice/schema for dynamic schema mapping
export { getDefaults } from '@practice/schema'

// Application
export type { GetDefaultTexturePatterns, GetDefaultMaskPatterns, GetSurfacePresets } from './Application'
export {
  createUniforms,
  createTexturePatternSpec,
  createTexturePatternFromPreset,
  createTexturePatternsFromPresets,
} from './Application'

// Infra
export { getDefaultTexturePatterns, getDefaultMaskPatterns, getSurfacePresets } from './Infra'

// Text rendering
export { renderTextToBitmap, type TextRenderOptions, type TextRenderResult } from './text/renderTextToCanvas'
export { createPositionedImageSpec, anchorToNumbers, type PositionedImageParams } from './shaders'
