// Google Fonts API
// https://developers.google.com/fonts/docs/developer_api

import type { GoogleFontsResponse, GoogleFontsQueryParams } from './types'
import { toFontPresets, type FontPreset } from './convert'

export type FetchGoogleFontsOptions = {
  apiKey: string
  limit?: number
}

export type FetchGoogleFontsResult = {
  totalFetched: number
  presets: FontPreset[]
}

function buildUrl(params: GoogleFontsQueryParams): string {
  const base = 'https://www.googleapis.com/webfonts/v1/webfonts'
  const searchParams = new URLSearchParams()

  searchParams.set('key', params.key)
  if (params.family) searchParams.set('family', params.family)
  if (params.subset) searchParams.set('subset', params.subset)
  if (params.category) searchParams.set('category', params.category)
  if (params.capability) searchParams.set('capability', params.capability)
  if (params.sort) searchParams.set('sort', params.sort)

  return `${base}?${searchParams.toString()}`
}

export async function fetchGoogleFonts(
  options: FetchGoogleFontsOptions
): Promise<FetchGoogleFontsResult> {
  const { apiKey, limit = 100 } = options

  const url = buildUrl({
    key: apiKey,
    sort: 'popularity',
  })

  const response = await fetch(url)
  const data: GoogleFontsResponse = await response.json()

  const totalFetched = data.items?.length ?? 0
  const items = limit > 0 ? data.items?.slice(0, limit) : data.items
  const presets = toFontPresets(items ?? [])

  return { totalFetched, presets }
}

export function generateTsFile(presets: FontPreset[]): string {
  const json = JSON.stringify(presets, null, 2)
  return `// Auto-generated by @tools/google-fonts
// Do not edit manually

import type { FontPreset } from '@practice/font'

export const GoogleFontPresets: FontPreset[] = ${json}
`
}
