export type {
  RGBA,
  TextureRenderOptions,
  Viewport,
  TexturePattern,
  MaskShapeType,
  CircleMaskShapeConfig,
  RectMaskShapeConfig,
  BlobMaskShapeConfig,
  PerlinMaskShapeConfig,
  SimplexMaskShapeConfig,
  CurlMaskShapeConfig,
  LinearGradientMaskShapeConfig,
  RadialGradientMaskShapeConfig,
  BoxGradientMaskShapeConfig,
  WavyLineMaskShapeConfig,
  MaskShapeConfig,
  // New children-based MaskPattern types
  MaskPatternStaticValue,
  MaskPatternSurface,
  MaskPatternLayer,
  MaskPattern,
  LegacyMaskPattern,
} from './TexturePattern'
export { $static } from './TexturePattern'
export type {
  SurfaceType,
  GenericSurfaceParams,
  SurfacePreset,
} from './SurfacePreset'
export type { TextureRenderSpec } from './TextureRenderSpec'
export type {
  // Simple textures
  SolidPatternParams,
  StripePatternParams,
  GridPatternParams,
  PolkaDotPatternParams,
  SimpleTexturePatternParams,
  // Masks
  CircleMaskPatternParams,
  RectMaskPatternParams,
  MaskPatternParams,
  // Masked textures
  CircleStripePatternParams,
  CircleGridPatternParams,
  CirclePolkaDotPatternParams,
  RectStripePatternParams,
  RectGridPatternParams,
  RectPolkaDotPatternParams,
  BlobStripePatternParams,
  BlobGridPatternParams,
  BlobPolkaDotPatternParams,
  MaskedTexturePatternParams,
  // Filters
  VignettePatternParams,
  ChromaticAberrationPatternParams,
  FilterPatternParams,
  // Gradient / Noise
  ColorStop,
  LinearGradientPatternParams,
  GradientGrainPatternParams,
  GradientPatternParams,
  // Union
  TexturePatternParams,
  // Spec
  TexturePatternSpec,
  CreateUniformsFn,
} from './TexturePatternSpec'

// Shape and Surface Schemas
export {
  // Shape Schemas
  CircleMaskShapeSchema,
  RectMaskShapeSchema,
  BlobMaskShapeSchema,
  PerlinMaskShapeSchema,
  SimplexMaskShapeSchema,
  CurlMaskShapeSchema,
  LinearGradientMaskShapeSchema,
  RadialGradientMaskShapeSchema,
  BoxGradientMaskShapeSchema,
  WavyLineMaskShapeSchema,
  MaskShapeSchemas,
  // Surface Schemas
  SolidSurfaceSchema,
  StripeSurfaceSchema,
  GridSurfaceSchema,
  PolkaDotSurfaceSchema,
  CheckerSurfaceSchema,
  LinearGradientSurfaceSchema,
  GradientGrainLinearSurfaceSchema,
  GradientGrainCircularSurfaceSchema,
  GradientGrainRadialSurfaceSchema,
  GradientGrainPerlinSurfaceSchema,
  GradientGrainCurlSurfaceSchema,
  GradientGrainSimplexSurfaceSchema,
  TriangleSurfaceSchema,
  HexagonSurfaceSchema,
  AsanohaSurfaceSchema,
  SeigaihaSurfaceSchema,
  WaveSurfaceSchema,
  ScalesSurfaceSchema,
  OgeeSurfaceSchema,
  SunburstSurfaceSchema,
  SurfaceSchemas,
  // Constants
  DEFAULT_GRADIENT_GRAIN_CURVE_POINTS,
  // Factory functions
  createDefaultCircleMaskParams,
  createDefaultRectMaskParams,
  createDefaultBlobMaskParams,
  createDefaultPerlinMaskParams,
  createDefaultSimplexMaskParams,
  createDefaultCurlMaskParams,
  createDefaultLinearGradientMaskParams,
  createDefaultRadialGradientMaskParams,
  createDefaultBoxGradientMaskParams,
  createDefaultWavyLineMaskParams,
  createDefaultSolidParams,
  createDefaultStripeParams,
  createDefaultGridParams,
  createDefaultPolkaDotParams,
  createDefaultCheckerParams,
  createDefaultLinearGradientParams,
  createDefaultGradientGrainLinearParams,
  createDefaultGradientGrainCircularParams,
  createDefaultGradientGrainRadialParams,
  createDefaultGradientGrainPerlinParams,
  createDefaultGradientGrainCurlParams,
  createDefaultGradientGrainSimplexParams,
  createDefaultTriangleParams,
  createDefaultHexagonParams,
} from './Schemas'
export type {
  CircleMaskShapeParams,
  RectMaskShapeParams,
  BlobMaskShapeParams,
  PerlinMaskShapeParams,
  SimplexMaskShapeParams,
  CurlMaskShapeParams,
  LinearGradientMaskShapeParams,
  RadialGradientMaskShapeParams,
  BoxGradientMaskShapeParams,
  WavyLineMaskShapeParams,
  SolidSurfaceParams,
  StripeSurfaceParams,
  GridSurfaceParams,
  PolkaDotSurfaceParams,
  CheckerSurfaceParams,
  LinearGradientSurfaceParams,
  GradientGrainLinearSurfaceParams,
  GradientGrainCircularSurfaceParams,
  GradientGrainRadialSurfaceParams,
  GradientGrainPerlinSurfaceParams,
  GradientGrainCurlSurfaceParams,
  GradientGrainSimplexSurfaceParams,
  TriangleSurfaceParams,
  HexagonSurfaceParams,
  AsanohaSurfaceParams,
  SeigaihaSurfaceParams,
  WaveSurfaceParams,
  ScalesSurfaceParams,
  OgeeSurfaceParams,
  SunburstSurfaceParams,
} from './Schemas'
// Greymap types (2-stage mask pipeline)
export type {
  GreymapMaskParams,
  GreymapMaskSpec,
  // Mask greymap types
  CircleGreymapMaskParams,
  RectGreymapMaskParams,
  BlobGreymapMaskParams,
  PerlinGreymapMaskParams,
  LinearGradientGreymapMaskParams,
  RadialGradientGreymapMaskParams,
  BoxGradientGreymapMaskParams,
  // Pattern greymap types
  StripeGreymapParams,
  GridGreymapParams,
  PolkaDotGreymapParams,
  CheckerGreymapParams,
  // Image greymap types
  ImageGreymapParams,
  // Colorize types
  ColorizeParams,
  CreateGreymapMaskSpecFn,
} from './GreymapSpec'
