export type {
  RGBA,
  TextureRenderOptions,
  Viewport,
  TexturePattern,
  MaskShapeType,
  CircleMaskShapeConfig,
  RectMaskShapeConfig,
  BlobMaskShapeConfig,
  PerlinMaskShapeConfig,
  MaskShapeConfig,
  MaskPattern,
} from './TexturePattern'
export type {
  SurfacePresetType,
  DepthMapType,
  SolidPresetParams,
  StripePresetParams,
  GridPresetParams,
  PolkaDotPresetParams,
  CheckerPresetParams,
  GradientGrainPresetParams,
  TrianglePresetParams,
  HexagonPresetParams,
  AsanohaPresetParams,
  SeigaihaPresetParams,
  WavePresetParams,
  ScalesPresetParams,
  OgeePresetParams,
  SunburstPresetParams,
  SurfacePresetParams,
  SurfacePreset,
} from './SurfacePreset'
export type { TextureRenderSpec } from './TextureRenderSpec'
export type {
  // Simple textures
  SolidPatternParams,
  StripePatternParams,
  GridPatternParams,
  PolkaDotPatternParams,
  SimpleTexturePatternParams,
  // Masks
  CircleMaskPatternParams,
  RectMaskPatternParams,
  MaskPatternParams,
  // Masked textures
  CircleStripePatternParams,
  CircleGridPatternParams,
  CirclePolkaDotPatternParams,
  RectStripePatternParams,
  RectGridPatternParams,
  RectPolkaDotPatternParams,
  BlobStripePatternParams,
  BlobGridPatternParams,
  BlobPolkaDotPatternParams,
  MaskedTexturePatternParams,
  // Filters
  VignettePatternParams,
  ChromaticAberrationPatternParams,
  FilterPatternParams,
  // Gradient / Noise
  ColorStop,
  LinearGradientPatternParams,
  GradientGrainPatternParams,
  GradientPatternParams,
  // Union
  TexturePatternParams,
  // Spec
  TexturePatternSpec,
  CreateUniformsFn,
} from './TexturePatternSpec'

// Shape and Surface Schemas
export {
  // Shape Schemas
  CircleMaskShapeSchema,
  RectMaskShapeSchema,
  BlobMaskShapeSchema,
  PerlinMaskShapeSchema,
  MaskShapeSchemas,
  // Surface Schemas
  SolidSurfaceSchema,
  StripeSurfaceSchema,
  GridSurfaceSchema,
  PolkaDotSurfaceSchema,
  CheckerSurfaceSchema,
  GradientGrainSurfaceSchema,
  TriangleSurfaceSchema,
  HexagonSurfaceSchema,
  AsanohaSurfaceSchema,
  SeigaihaSurfaceSchema,
  WaveSurfaceSchema,
  ScalesSurfaceSchema,
  OgeeSurfaceSchema,
  SunburstSurfaceSchema,
  SurfaceSchemas,
  // Constants
  DEFAULT_GRADIENT_GRAIN_CURVE_POINTS,
  // Factory functions
  createDefaultCircleMaskParams,
  createDefaultRectMaskParams,
  createDefaultBlobMaskParams,
  createDefaultPerlinMaskParams,
  createDefaultSolidParams,
  createDefaultStripeParams,
  createDefaultGridParams,
  createDefaultPolkaDotParams,
  createDefaultCheckerParams,
  createDefaultGradientGrainParams,
  createDefaultTriangleParams,
  createDefaultHexagonParams,
} from './Schemas'
export type {
  CircleMaskShapeParams,
  RectMaskShapeParams,
  BlobMaskShapeParams,
  PerlinMaskShapeParams,
  SolidSurfaceParams,
  StripeSurfaceParams,
  GridSurfaceParams,
  PolkaDotSurfaceParams,
  CheckerSurfaceParams,
  GradientGrainSurfaceParams,
  TriangleSurfaceParams,
  HexagonSurfaceParams,
  AsanohaSurfaceParams,
  SeigaihaSurfaceParams,
  WaveSurfaceParams,
  ScalesSurfaceParams,
  OgeeSurfaceParams,
  SunburstSurfaceParams,
} from './Schemas'
