// Auto-generated by @tools/google-fonts
// Do not edit manually

import type { FontPreset } from '../Domain/ValueObject'

export const GoogleFontPresets: FontPreset[] = [
  {
    "id": "roboto",
    "name": "Roboto",
    "family": "'Roboto', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "open-sans",
    "name": "Open Sans",
    "family": "'Open Sans', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Open%20Sans:wght@300;400;500;600;700;800&display=swap"
    }
  },
  {
    "id": "noto-sans-jp",
    "name": "Noto Sans JP",
    "family": "'Noto Sans JP', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Noto%20Sans%20JP:wght@100;200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "montserrat",
    "name": "Montserrat",
    "family": "'Montserrat', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "inter",
    "name": "Inter",
    "family": "'Inter', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "poppins",
    "name": "Poppins",
    "family": "'Poppins', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "lato",
    "name": "Lato",
    "family": "'Lato', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Lato:wght@100;300;400;700;900&display=swap"
    }
  },
  {
    "id": "material-icons",
    "name": "Material Icons",
    "family": "'Material Icons', monospace",
    "category": "monospace",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Material%20Icons:wght@400&display=swap"
    }
  },
  {
    "id": "roboto-condensed",
    "name": "Roboto Condensed",
    "family": "'Roboto Condensed', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Roboto%20Condensed:wght@100;200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "arimo",
    "name": "Arimo",
    "family": "'Arimo', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Arimo:wght@400;500;600;700&display=swap"
    }
  },
  {
    "id": "oswald",
    "name": "Oswald",
    "family": "'Oswald', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400;500;600;700&display=swap"
    }
  },
  {
    "id": "roboto-mono",
    "name": "Roboto Mono",
    "family": "'Roboto Mono', monospace",
    "category": "monospace",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Roboto%20Mono:wght@100;200;300;400;500;600;700&display=swap"
    }
  },
  {
    "id": "noto-sans",
    "name": "Noto Sans",
    "family": "'Noto Sans', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Noto%20Sans:wght@100;200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "raleway",
    "name": "Raleway",
    "family": "'Raleway', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Raleway:wght@100;200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "nunito-sans",
    "name": "Nunito Sans",
    "family": "'Nunito Sans', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Nunito%20Sans:wght@200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "nunito",
    "name": "Nunito",
    "family": "'Nunito', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Nunito:wght@200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "playfair-display",
    "name": "Playfair Display",
    "family": "'Playfair Display', serif",
    "category": "serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Playfair%20Display:wght@400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "kanit",
    "name": "Kanit",
    "family": "'Kanit', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Kanit:wght@100;200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "rubik",
    "name": "Rubik",
    "family": "'Rubik', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "ubuntu",
    "name": "Ubuntu",
    "family": "'Ubuntu', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Ubuntu:wght@300;400;500;700&display=swap"
    }
  },
  {
    "id": "dm-sans",
    "name": "DM Sans",
    "family": "'DM Sans', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=DM%20Sans:wght@100;200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "roboto-slab",
    "name": "Roboto Slab",
    "family": "'Roboto Slab', serif",
    "category": "serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Roboto%20Slab:wght@100;200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "noto-sans-kr",
    "name": "Noto Sans KR",
    "family": "'Noto Sans KR', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Noto%20Sans%20KR:wght@100;200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "work-sans",
    "name": "Work Sans",
    "family": "'Work Sans', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Work%20Sans:wght@100;200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "merriweather",
    "name": "Merriweather",
    "family": "'Merriweather', serif",
    "category": "serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Merriweather:wght@300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "lora",
    "name": "Lora",
    "family": "'Lora', serif",
    "category": "serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Lora:wght@400;500;600;700&display=swap"
    }
  },
  {
    "id": "pt-sans",
    "name": "PT Sans",
    "family": "'PT Sans', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=PT%20Sans:wght@400;700&display=swap"
    }
  },
  {
    "id": "mulish",
    "name": "Mulish",
    "family": "'Mulish', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Mulish:wght@200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "material-symbols-outlined",
    "name": "Material Symbols Outlined",
    "family": "'Material Symbols Outlined', monospace",
    "category": "monospace",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Material%20Symbols%20Outlined:wght@100;200;300;400;500;600;700&display=swap"
    }
  },
  {
    "id": "figtree",
    "name": "Figtree",
    "family": "'Figtree', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Figtree:wght@300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "noto-sans-tc",
    "name": "Noto Sans TC",
    "family": "'Noto Sans TC', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Noto%20Sans%20TC:wght@100;200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "manrope",
    "name": "Manrope",
    "family": "'Manrope', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Manrope:wght@200;300;400;500;600;700;800&display=swap"
    }
  },
  {
    "id": "outfit",
    "name": "Outfit",
    "family": "'Outfit', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Outfit:wght@100;200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "hind-siliguri",
    "name": "Hind Siliguri",
    "family": "'Hind Siliguri', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Hind%20Siliguri:wght@300;400;500;600;700&display=swap"
    }
  },
  {
    "id": "barlow",
    "name": "Barlow",
    "family": "'Barlow', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Barlow:wght@100;200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "quicksand",
    "name": "Quicksand",
    "family": "'Quicksand', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap"
    }
  },
  {
    "id": "ibm-plex-sans",
    "name": "IBM Plex Sans",
    "family": "'IBM Plex Sans', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=IBM%20Plex%20Sans:wght@100;200;300;400;500;600;700&display=swap"
    }
  },
  {
    "id": "fira-sans",
    "name": "Fira Sans",
    "family": "'Fira Sans', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Fira%20Sans:wght@100;200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "bebas-neue",
    "name": "Bebas Neue",
    "family": "'Bebas Neue', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Bebas%20Neue:wght@400&display=swap"
    }
  },
  {
    "id": "karla",
    "name": "Karla",
    "family": "'Karla', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Karla:wght@200;300;400;500;600;700;800&display=swap"
    }
  },
  {
    "id": "titillium-web",
    "name": "Titillium Web",
    "family": "'Titillium Web', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Titillium%20Web:wght@200;300;400;600;700;900&display=swap"
    }
  },
  {
    "id": "source-sans-3",
    "name": "Source Sans 3",
    "family": "'Source Sans 3', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Source%20Sans%203:wght@200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "jost",
    "name": "Jost",
    "family": "'Jost', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Jost:wght@100;200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "prompt",
    "name": "Prompt",
    "family": "'Prompt', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Prompt:wght@100;200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "pt-serif",
    "name": "PT Serif",
    "family": "'PT Serif', serif",
    "category": "serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=PT%20Serif:wght@400;700&display=swap"
    }
  },
  {
    "id": "noto-serif",
    "name": "Noto Serif",
    "family": "'Noto Serif', serif",
    "category": "serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Noto%20Serif:wght@100;200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "heebo",
    "name": "Heebo",
    "family": "'Heebo', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Heebo:wght@100;200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "archivo",
    "name": "Archivo",
    "family": "'Archivo', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Archivo:wght@100;200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "material-icons-outlined",
    "name": "Material Icons Outlined",
    "family": "'Material Icons Outlined', monospace",
    "category": "monospace",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Material%20Icons%20Outlined:wght@400&display=swap"
    }
  },
  {
    "id": "saira",
    "name": "Saira",
    "family": "'Saira', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Saira:wght@100;200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "inconsolata",
    "name": "Inconsolata",
    "family": "'Inconsolata', monospace",
    "category": "monospace",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Inconsolata:wght@200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "dancing-script",
    "name": "Dancing Script",
    "family": "'Dancing Script', cursive",
    "category": "handwriting",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Dancing%20Script:wght@400;500;600;700&display=swap"
    }
  },
  {
    "id": "libre-baskerville",
    "name": "Libre Baskerville",
    "family": "'Libre Baskerville', serif",
    "category": "serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Libre%20Baskerville:wght@400;500;600;700&display=swap"
    }
  },
  {
    "id": "josefin-sans",
    "name": "Josefin Sans",
    "family": "'Josefin Sans', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Josefin%20Sans:wght@100;200;300;400;500;600;700&display=swap"
    }
  },
  {
    "id": "noto-color-emoji",
    "name": "Noto Color Emoji",
    "family": "'Noto Color Emoji', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Noto%20Color%20Emoji:wght@400&display=swap"
    }
  },
  {
    "id": "barlow-condensed",
    "name": "Barlow Condensed",
    "family": "'Barlow Condensed', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Barlow%20Condensed:wght@100;200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "libre-franklin",
    "name": "Libre Franklin",
    "family": "'Libre Franklin', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Libre%20Franklin:wght@100;200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "anton",
    "name": "Anton",
    "family": "'Anton', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Anton:wght@400&display=swap"
    }
  },
  {
    "id": "schibsted-grotesk",
    "name": "Schibsted Grotesk",
    "family": "'Schibsted Grotesk', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Schibsted%20Grotesk:wght@400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "eb-garamond",
    "name": "EB Garamond",
    "family": "'EB Garamond', serif",
    "category": "serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=EB%20Garamond:wght@400;500;600;700;800&display=swap"
    }
  },
  {
    "id": "dosis",
    "name": "Dosis",
    "family": "'Dosis', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Dosis:wght@200;300;400;500;600;700;800&display=swap"
    }
  },
  {
    "id": "share-tech",
    "name": "Share Tech",
    "family": "'Share Tech', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Share%20Tech:wght@400&display=swap"
    }
  },
  {
    "id": "source-code-pro",
    "name": "Source Code Pro",
    "family": "'Source Code Pro', monospace",
    "category": "monospace",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Source%20Code%20Pro:wght@200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "smooch-sans",
    "name": "Smooch Sans",
    "family": "'Smooch Sans', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Smooch%20Sans:wght@100;200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "noto-serif-jp",
    "name": "Noto Serif JP",
    "family": "'Noto Serif JP', serif",
    "category": "serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Noto%20Serif%20JP:wght@200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "mukta",
    "name": "Mukta",
    "family": "'Mukta', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Mukta:wght@200;300;400;500;600;700;800&display=swap"
    }
  },
  {
    "id": "plus-jakarta-sans",
    "name": "Plus Jakarta Sans",
    "family": "'Plus Jakarta Sans', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Plus%20Jakarta%20Sans:wght@200;300;400;500;600;700;800&display=swap"
    }
  },
  {
    "id": "cairo",
    "name": "Cairo",
    "family": "'Cairo', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "cabin",
    "name": "Cabin",
    "family": "'Cabin', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Cabin:wght@400;500;600;700&display=swap"
    }
  },
  {
    "id": "archivo-black",
    "name": "Archivo Black",
    "family": "'Archivo Black', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Archivo%20Black:wght@400&display=swap"
    }
  },
  {
    "id": "nanum-gothic",
    "name": "Nanum Gothic",
    "family": "'Nanum Gothic', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Nanum%20Gothic:wght@400;700;800&display=swap"
    }
  },
  {
    "id": "noto-sans-sc",
    "name": "Noto Sans SC",
    "family": "'Noto Sans SC', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Noto%20Sans%20SC:wght@100;200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "public-sans",
    "name": "Public Sans",
    "family": "'Public Sans', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Public%20Sans:wght@100;200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "roboto-flex",
    "name": "Roboto Flex",
    "family": "'Roboto Flex', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Roboto%20Flex:wght@400&display=swap"
    }
  },
  {
    "id": "assistant",
    "name": "Assistant",
    "family": "'Assistant', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Assistant:wght@200;300;400;500;600;700;800&display=swap"
    }
  },
  {
    "id": "bitter",
    "name": "Bitter",
    "family": "'Bitter', serif",
    "category": "serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Bitter:wght@100;200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "pacifico",
    "name": "Pacifico",
    "family": "'Pacifico', cursive",
    "category": "handwriting",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Pacifico:wght@400&display=swap"
    }
  },
  {
    "id": "crimson-text",
    "name": "Crimson Text",
    "family": "'Crimson Text', serif",
    "category": "serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Crimson%20Text:wght@400;600;700&display=swap"
    }
  },
  {
    "id": "material-symbols-rounded",
    "name": "Material Symbols Rounded",
    "family": "'Material Symbols Rounded', monospace",
    "category": "monospace",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Material%20Symbols%20Rounded:wght@100;200;300;400;500;600;700&display=swap"
    }
  },
  {
    "id": "ramabhadra",
    "name": "Ramabhadra",
    "family": "'Ramabhadra', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Ramabhadra:wght@400&display=swap"
    }
  },
  {
    "id": "noto-sans-telugu",
    "name": "Noto Sans Telugu",
    "family": "'Noto Sans Telugu', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Noto%20Sans%20Telugu:wght@100;200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "anek-telugu",
    "name": "Anek Telugu",
    "family": "'Anek Telugu', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Anek%20Telugu:wght@100;200;300;400;500;600;700;800&display=swap"
    }
  },
  {
    "id": "inter-tight",
    "name": "Inter Tight",
    "family": "'Inter Tight', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Inter%20Tight:wght@100;200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "material-icons-round",
    "name": "Material Icons Round",
    "family": "'Material Icons Round', monospace",
    "category": "monospace",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Material%20Icons%20Round:wght@400&display=swap"
    }
  },
  {
    "id": "cormorant-garamond",
    "name": "Cormorant Garamond",
    "family": "'Cormorant Garamond', serif",
    "category": "serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Cormorant%20Garamond:wght@300;400;500;600;700&display=swap"
    }
  },
  {
    "id": "exo-2",
    "name": "Exo 2",
    "family": "'Exo 2', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Exo%202:wght@100;200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "red-hat-display",
    "name": "Red Hat Display",
    "family": "'Red Hat Display', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Red%20Hat%20Display:wght@300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "caveat",
    "name": "Caveat",
    "family": "'Caveat', cursive",
    "category": "handwriting",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Caveat:wght@400;500;600;700&display=swap"
    }
  },
  {
    "id": "oxygen",
    "name": "Oxygen",
    "family": "'Oxygen', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Oxygen:wght@300;400;700&display=swap"
    }
  },
  {
    "id": "lobster",
    "name": "Lobster",
    "family": "'Lobster', cursive",
    "category": "display",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Lobster:wght@400&display=swap"
    }
  },
  {
    "id": "slabo-27px",
    "name": "Slabo 27px",
    "family": "'Slabo 27px', serif",
    "category": "serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Slabo%2027px:wght@400&display=swap"
    }
  },
  {
    "id": "m-plus-rounded-1c",
    "name": "M PLUS Rounded 1c",
    "family": "'M PLUS Rounded 1c', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=M%20PLUS%20Rounded%201c:wght@100;300;400;500;700;800;900&display=swap"
    }
  },
  {
    "id": "hind",
    "name": "Hind",
    "family": "'Hind', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Hind:wght@300;400;500;600;700&display=swap"
    }
  },
  {
    "id": "space-grotesk",
    "name": "Space Grotesk",
    "family": "'Space Grotesk', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Space%20Grotesk:wght@300;400;500;600;700&display=swap"
    }
  },
  {
    "id": "alfa-slab-one",
    "name": "Alfa Slab One",
    "family": "'Alfa Slab One', cursive",
    "category": "display",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Alfa%20Slab%20One:wght@400&display=swap"
    }
  },
  {
    "id": "lexend",
    "name": "Lexend",
    "family": "'Lexend', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Lexend:wght@100;200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "arvo",
    "name": "Arvo",
    "family": "'Arvo', serif",
    "category": "serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Arvo:wght@400;700&display=swap"
    }
  },
  {
    "id": "comfortaa",
    "name": "Comfortaa",
    "family": "'Comfortaa', cursive",
    "category": "display",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Comfortaa:wght@300;400;500;600;700&display=swap"
    }
  },
  {
    "id": "urbanist",
    "name": "Urbanist",
    "family": "'Urbanist', sans-serif",
    "category": "sans-serif",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Urbanist:wght@100;200;300;400;500;600;700;800;900&display=swap"
    }
  },
  {
    "id": "changa-one",
    "name": "Changa One",
    "family": "'Changa One', cursive",
    "category": "display",
    "source": {
      "vendor": "google",
      "url": "https://fonts.googleapis.com/css2?family=Changa%20One:wght@400&display=swap"
    }
  }
]
